# Generated by Django 5.0.6 on 2024-07-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
