# Generated by Django 5.0.6 on 2024-07-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_formapago_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
