# Generated by Django 5.0.6 on 2024-06-30 20:38

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tipodeusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=usuarios.models.get_default_tipo_usuario, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodeusuario', verbose_name='Tipo de Usuario'),
        ),
    ]
