# Generated by Django 5.0.6 on 2024-07-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasenna',
        ),
    ]
