# Generated by Django 5.0.6 on 2024-07-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarroProducto',
        ),
    ]
